### ISSUE TITLE
Expose list of added/changed/deleted files

### ISSUE THREAD

**Issue by markuskobler** [ember-cli/broccoli-caching-writer#41]
If building a filter plugin, with a 1 to 1 mapping, it would be useful to have a diff of changed files. It seems like the current caching writer has all the info it needs to expose that information to an extending plugins but I'm unclear as to what the most friendly api would look like. 

As I see it there are two sublet complexities in exposing this information
- Simply returning a list of added and changed files is easy but deleted files should also be returned
- The plugin still needs to return a complete list of files, including the files not rebuilt, so as not to break broccoli subsequent rebuilds.

Are there any thoughts to implement something like this?

**Comment by zackthehuman** [comment]
I also think this would be a nice addition to the API. Since I have several use cases where I map multiple files to a set of fewer files, or sometimes many files to a single file. I could implement much more efficient code if I knew which files were changed rather than just knowing that _something_ in the tree changed. Perhaps the `updateCache` method could have two additional parameters -- `changedPaths` and `removedPaths`? An added file would count as a "change" if it wasn't present during the previous build.

**Comment by knownasilya** [comment]
>  An added file would count as a "change" if it wasn't present during the previous build.

I don't think that works, because if you didn't change the file previously, the next run it wouldn't be there, then you could think it was a new file on the next run if there was a change.

**Comment by stefanpenner** [comment]
the new FSTree diff infrastructure provides this (or similar data) I have some plans to evolve it slightly further and expose such things here.

(so this is not forgotten)

**Comment by zackthehuman** [comment]
@stefanpenner Pinging this issue. I think it should be possible to expose the diff when calling `build` at this point. I might experiment with it and see how it goes...

**Comment by stefanpenner** [comment]
@zackthehuman i honestly think at that point, caching writer is the wrong abstraction. And BroccoliPlugin + walkSync + fs-tree is more friendly.

**Comment by zackthehuman** [comment]
In lieu of this issue being closed I have published `broccoli-diffing-writer` which computes a diff between builds/rebuilds: https://github.com/zackthehuman/broccoli-diffing-writer

Thanks for the idea!
